# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

[ -f "$HOME/AppData/Roaming/dystroy/broot/config/launcher/bash/br" ] && source $HOME/AppData/Roaming/dystroy/broot/config/launcher/bash/br

